# Generated by Django 4.0.5 on 2022-06-17 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('video_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('channel_name', models.CharField(max_length=30)),
                ('published_at', models.DateTimeField(default=datetime.datetime(2022, 6, 17, 19, 27, 15, 131422))),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
