# Generated by Django 4.0.5 on 2022-06-17 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_youtubevideo_delete_youtubevideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('is_expired', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('expired_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='channel_name',
            new_name='channel_title',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='thumbnail_urls',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 23, 12, 56, 744339)),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
