# Generated by Django 4.0.5 on 2022-06-18 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_alter_apikey_expired_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expired_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 6, 0, 47, 737256)),
        ),
    ]
